In [1]:
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Analyzing movie posters with BigQuery Dataframe AI functions

<table align="left">

  <td>
    <a href="https://colab.research.google.com/github/googleapis/python-bigquery-dataframes/blob/main/notebooks/generative_ai/ai_movie_poster.ipynb">
      <img src="https://raw.githubusercontent.com/googleapis/python-bigquery-dataframes/refs/heads/main/third_party/logo/colab-logo.png" alt="Colab logo"> Run in Colab
    </a>
  </td>
  <td>
    <a href="https://github.com/googleapis/python-bigquery-dataframes/blob/main/notebooks/generative_ai/ai_movie_poster.ipynb">
      <img src="https://raw.githubusercontent.com/googleapis/python-bigquery-dataframes/refs/heads/main/third_party/logo/github-logo.png" width="32" alt="GitHub logo">
      View on GitHub
    </a>
  </td>
  <td>
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/googleapis/python-bigquery-dataframes/blob/main/notebooks/generative_ai/ai_movie_poster.ipynb">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW1gvOovVlbZAIZylUtf5Iu8-693qS1w5NJw&s" alt="BQ logo" width="35">
      Open in BQ Studio
    </a>
  </td>
</table>

BigQuery Dataframe provides a Pythonic way to use AI functions directly with your dataframes. In this notebook, you will use these functions to analyze old
movie posters. These posters are images stored in a public Google Cloud Storage bucket: `gs://cloud-samples-data/vertex-ai/dataset-management/datasets/classic-movie-posters`

## Set up

Before you begin, you need to

* Set up your permissions for generative AI functions with [these instructions](https://docs.cloud.google.com/bigquery/docs/permissions-for-ai-functions)
* Set up your Cloud Resource connection by following [these instructions](https://docs.cloud.google.com/bigquery/docs/create-cloud-resource-connection)

Once you have the permissions set up, import the `bigframes.pandas` package, and
set your cloud project ID.

In [ ]:
import bigframes.pandas as bpd

MY_RPOJECT_ID = "bigframes-dev" # @param {type:"string"}

bpd.options.bigquery.project = MY_RPOJECT_ID

## Load data

First, you load the data from the GCS bucket to a BigQuery Dataframe with the `from_glob_path` method:

In [ ]:
# Replace with your own connection name.\nMY_CONNECTION = 'bigframes-default-connection' # @param {type:"string"}\n\nimport bigframes.pandas as bpd\nsession = bpd.get_global_session()\n\nmovies = session._from_glob_path(\n    "gs://cloud-samples-data/vertex-ai/dataset-management/datasets/classic-movie-posters/*",\n    connection = MY_CONNECTION,\n    name='poster')\nmovies.head(1)

/usr/local/lib/python3.12/dist-packages/bigframes/core/global_session.py:113: DefaultLocationWarning: No explicit location is set, so using location US for the session.
  _global_session = bigframes.session.connect(

/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:1010: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)

                                              poster
0  {"access_urls":{"expiry_time":"2026-03-27T02:0...

[1 rows x 1 columns]

## Extract titles from posters

In [4]:
import bigframes.bigquery as bbq

movies['title'] = bbq.ai.generate(
    ("What is the movie title for this poster? Name only", movies['poster']),
    endpoint='gemini-2.5-pro'
).struct.field("result")
movies.head(1)

/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:1010: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:1010: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)

                                              poster                 title
0  {"access_urls":{"expiry_time":"2026-03-27T02:0...  Der Student von Prag

[1 rows x 2 columns]

Notice that `ai.generate()` has a `struct` return type, which holds not only the LLM response, but also the status. If you do not provide a field name for your answer, `"result"` will be the default name. You can access LLM response content with the struct accessor (e.g. `my_response.struct.filed("result")`);.

## Get movie release year

In the example below, you will use `ai.generate_int()` to find the release year for each movie poster:

In [5]:
movies['year'] = bbq.ai.generate_int(
    ("What is the release year for this movie?", movies['title']),
    endpoint='gemini-2.5-pro'
).struct.field("result")

movies.head(1)

/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:1010: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)

,poster,title,year
0,"<img src=""https://storage.googleapis.com/cloud-samples-data/vertex-ai%2Fdataset-management%2Fdatasets%2Fclassic-movie-posters%2Fder_student_von_prag.jpg?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260326%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260326T200120Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1683653080624441&X-Goog-Signature=96035b9c90093c9636f0b406e5ca9daf52bb1019bde4d52e779f3ce7371e6df0430b3f2e991869065e113327a7698e7ce5ad7b4db8781aa65adea890b80976c97b93b3f9deac5002a1e27b4bd2c1df9250ff4167f150c88be2067f70d45b7c94fd6d69f36a90b5a3ad1a3d500e3cc89a4fe4a67157cbea164d5ce34506dd1d2353eedb1c663eb1a4578c8ff1f9af2ab21a7065de4ec3ff1af44e764a3215874e564e6beeb502739468a80a02c79dcc71f7518435686270d855007e01653659804b5f50ab9c43c4627f28625e07572a4b0f30de49397f9f0445571cdacb695747bdb17614addcf33a90036aa48d025baa8a4d6bd5000d0106a788c2c23f1292c8"">",Der Student von Prag,1913

In [6]:
movies.dtypes

/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:1010: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)

poster    struct<uri: string, version: string, authorize...
title                                       string[pyarrow]
year                                                  Int64
dtype: object

## Filter movie by production country

In the next example, you will use `ai.if_()` to find the movies that were produced in the USA.

In [7]:
us_movies = movies[bbq.ai.if_(
    ("The movie ", movies['title'], " was made in US")
)]
us_movies.head(1)

/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:1010: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)

                                              poster          title  year
8  {"access_urls":{"expiry_time":"2026-03-27T02:0...  Shoulder Arms  1918

[1 rows x 3 columns]