# Describe product images with BigFrames multimodal DataFrames

Based on notebook at https://github.com/googleapis/python-bigquery-dataframes/blob/main/notebooks/multimodal/multimodal_dataframe.ipynb

This notebook is introducing BigFrames Multimodal features:

1. Create Multimodal DataFrame
2. Combine unstructured data with structured data
3. Conduct image transformations
4. Use LLM models to ask questions and generate embeddings on images
5. PDF chunking function

Install the bigframes package and upgrade other packages that are already included in Kaggle but have versions incompatible with bigframes.

In [ ]:
%pip install --upgrade bigframes google-cloud-automl google-cloud-translate google-ai-generativelanguage tensorflow

**Important:** restart the kernel by going to "Run -> Restart & clear cell outputs" before continuing.

Configure bigframes to use your GCP project. First, go to "Add-ons -> Google Cloud SDK" and click the "Attach" button. Then,

In [2]:
try:
    from kaggle_secrets import UserSecretsClient
    user_secrets = UserSecretsClient()
    user_credential = user_secrets.get_gcloud_credential()
    user_secrets.set_tensorflow_credential(user_credential)
    print("Successfully authenticated using Kaggle secrets.")
except ImportError:
    print("Not running on Kaggle, skipping Kaggle secrets initialization.")
except Exception as e:
    print(f"Could not initialize Kaggle secrets: {e}")

In [3]:
PROJECT = "bigframes-dev" # replace with your project. 
# Refer to https://cloud.google.com/bigquery/docs/multimodal-data-dataframes-tutorial#required_roles for your required permissions

LOCATION = "us" # replace with your location.
DATASET_ID = "bigframes_samples" # replace with your dataset ID.
OUTPUT_BUCKET = "bigframes_blob_test" # replace with your GCS bucket. 

FULL_CONNECTION_ID = f"{PROJECT}.{LOCATION}.bigframes-default-connection"

import bigframes
# Setup project
bigframes.options.bigquery.project = PROJECT
bigframes.options.bigquery.location = LOCATION

# Display options
bigframes.options.display.blob_display_width = 300
bigframes.options.display.progress_bar = None

import bigframes.pandas as bpd
import bigframes.bigquery as bbq

def get_runtime_json_str(series, mode="R", with_metadata=False):
    """Get runtime JSON from objectref."""
    s = bbq.obj.fetch_metadata(series) if with_metadata else series
    runtime = bbq.obj.get_access_url(s, mode=mode)
    return bbq.to_json_string(runtime)

def get_metadata(series):
    metadata_obj = bbq.obj.fetch_metadata(series)
    return bbq.json_query(metadata_obj.struct.field("details"), "$.gcs_metadata")

def get_content_type(series):
    return bbq.json_value(get_metadata(series), "$.content_type")

def get_size(series):
    return bbq.json_value(get_metadata(series), "$.size").astype("Int64")

def get_updated(series):
    return bpd.to_datetime(bbq.json_value(get_metadata(series), "$.updated").astype("Int64"), unit="us", utc=True)

from IPython.display import HTML, display

def render_images(df):
    """Helper to display BigFrames DataFrame with rendered image previews."""
    import bigframes.pandas as bpd
    import bigframes.bigquery as bbq
    import bigframes
    from bigframes import dtypes
    import json
    
    if isinstance(df, bpd.Series):
        df = df.to_frame()
        
    object_cols = [
        col for col, dtype in zip(df.columns, df.dtypes)
        if dtype == dtypes.OBJ_REF_DTYPE
    ]
    
    if not object_cols:
        display(df)
        return

    limit = bigframes.options.display.max_rows or 10
    view_df = df.head(limit)
        
    runtime_cols = {
        col: get_runtime_json_str(view_df[col], mode="R", with_metadata=False) 
        for col in object_cols
    }
        
    pandas_json_df = bpd.DataFrame(runtime_cols).to_pandas()
    final_pd = view_df.to_pandas()
    
    width = bigframes.options.display.blob_display_width or 300
    IMAGE_EXTENSIONS = (".png", ".jpg", ".jpeg", ".gif", ".webp")
    
    def format_cell_html(raw_json):
        if not raw_json:
            return ""
        try:
            obj_rt = json.loads(raw_json)
            if "access_urls" not in obj_rt:
                err = obj_rt.get("errors", [{"message": "URL Generation Failed"}])[0].get("message")
                return f'<span style="color:red;">Error: {err}</span>'
                
            uri = obj_rt.get("objectref", {}).get("uri", "")
            url = obj_rt["access_urls"]["read_url"]
            
            if uri and str(uri).lower().endswith(IMAGE_EXTENSIONS):
                return f'<img src="{url}" width="{width}">'
            
            return f'<a href="{url}" target="_blank">{uri if uri else "view"}</a>'
        except:
            return "Format Error"

    for col in object_cols:
        final_pd[col] = pandas_json_df[col].map(format_cell_html)
        
    display(HTML(final_pd.to_html(escape=False)))

In [4]:
import gcsfs
import bigframes.bigquery as bbq

# List files using gcsfs (public bucket)
fs = gcsfs.GCSFileSystem(anon=True)
uris = fs.glob("gs://cloud-samples-data/bigquery/tutorials/cymbal-pets/images/*")

# Ensure URIs have gs:// prefix
uris = [u if u.startswith("gs://") else f"gs://{u}" for u in uris]

# Read the URIs into a BigQuery DataFrame using UNNEST
# We take the first 5 for this example
df_image = bpd.read_gbq(f"SELECT uri FROM UNNEST({uris[:5]}) as uri")

# Create the object reference column
df_image['image'] = bbq.obj.make_ref(df_image['uri'], authorizer=FULL_CONNECTION_ID)
df_image = df_image[['image']]

/usr/local/lib/python3.11/dist-packages/bigframes/core/global_session.py:103: DefaultLocationWarning: No explicit location is set, so using location US for the session.
  _global_session = bigframes.session.connect(

Please ensure you have selected a BigQuery account in the Notebook Add-ons menu.

In [5]:
# Take only the 5 images to deal with. Preview the content of the Mutimodal DataFrame
df_image = df_image.head(5)
render_images(df_image)

                                               image
0  {'uri': 'gs://cloud-samples-data/bigquery/tuto...
1  {'uri': 'gs://cloud-samples-data/bigquery/tuto...
2  {'uri': 'gs://cloud-samples-data/bigquery/tuto...
3  {'uri': 'gs://cloud-samples-data/bigquery/tuto...
4  {'uri': 'gs://cloud-samples-data/bigquery/tuto...

[5 rows x 1 columns]

# 2. Combine unstructured data with structured data

Now you can put more information into the table to describe the files. Such as author info from inputs, or other metadata from the gcs object itself.

In [6]:
# Combine unstructured data with structured data
df_image["author"] = ["alice", "bob", "bob", "alice", "bob"] # type: ignore
df_image["content_type"] = get_content_type(df_image["image"])
df_image["size"] = get_size(df_image["image"])
df_image["updated"] = get_updated(df_image["image"])
render_images(df_image)

/usr/local/lib/python3.11/dist-packages/bigframes/bigquery/_operations/json.py:124: UserWarning: The `json_extract` is deprecated and will be removed in a future
version. Use `json_query` instead.
  warnings.warn(bfe.format_message(msg), category=UserWarning)
/usr/local/lib/python3.11/dist-packages/bigframes/bigquery/_operations/json.py:124: UserWarning: The `json_extract` is deprecated and will be removed in a future
version. Use `json_query` instead.
  warnings.warn(bfe.format_message(msg), category=UserWarning)
/usr/local/lib/python3.11/dist-packages/bigframes/bigquery/_operations/json.py:124: UserWarning: The `json_extract` is deprecated and will be removed in a future
version. Use `json_query` instead.
  warnings.warn(bfe.format_message(msg), category=UserWarning)

,image,author,content_type,size,updated
0,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-paw-balm.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T201823Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492703986347&X-Goog-Signature=8f2857f42b8ba3abed9e60449cc32b150cbd6276a923a6d85e5c06ddde834849f9dc25a05a7cd56627308c78d68f471dc14d220573d9a5564fe3b03acbeb1776414a54ab717e65a0039b2beb31092dcb7d58a2aefd8d0b0063904e330a7aa424e06c99205b5b83c9efe3111db07e9571224cc2aff52f71dad9f6b68a7afa9099803c2476a058002ac1b01f1cb6614230cccb1c730ca16c69dfa6142b255032cc799a33c1dd2cfacfd2d4db3fcfa8b8fd0ed68711bfba781d1119192fe24fe667aa129f8d1908702b295eb2d57d7782006d8c77e4a27ba6b1d3adad801ac9c859e0162db46834407d19942af2bd94c9d698b1c5352c7c9d8af58c956f607c3f10"" width=""300"">",alice,image/png,1591240,2025-03-20 17:45:04+00:00
1,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-hot-spot-spray.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T201823Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492702954473&X-Goog-Signature=9fbf42a56019dfd8b35e8d29981674906d025145bac8a5d9cebadfda4d04420ed34e2d554973a4084252f5ecc2803e82fd6817a2338ce9159fe5140d4a3a77cdc7e5feed733ad2b4351ce97fe82f76de1e5523022fdf12543cbf48827b07641bdd3083d0f8c11d95a46d1af17b70968e1f30ad99bf305ab8b5a827f24d5980a28df3726111f7f79c2444f78bfe5268d6ed2bbb172d368930b27690b635bdbd5cbfca7264b4e0bb0b170ac3dd15a9c36c3e77061906958464c8c610bb11b98602f99a184dca788ff5b154259c944e536fdeb47988c3ed9430e5fafd86e5c9b05088dd72c5f9f25516d0dead404dff0c0b2e4a91993a43100c66588ed373314e74"" width=""300"">",bob,image/png,1182951,2025-03-20 17:45:02+00:00
2,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Ffluffy-buns-chinchilla-food-variety-pack.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T201823Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492694988945&X-Goog-Signature=7ee0d2c8dbcc174ef6edb76725adde283ec45db4f733d02241b350bb3af4094e97dbcedcbc98091c28273d51cd059ca475d501dad445ef4dd335c1add9930196a172adc8d45beda0003f934610167c022be84e43774af7b7805ba526d39509c68f065c6bc442196df71330bfeb9910ba4b85a1bf1defd6ebb34b6d0ed092c795c006d4bec18931cc00b9678f1a8cd43b2ee46efc9c03418e182dba57f61e011d8de299482a5c94763eaecda94b914254c34e635644944c9c14cf90d2a57d05767dc9330890dcd526c91d771b1182b47e23163db8d29e6146356355724e9bb854c9e246f1c376be69b1b32d5039ff42ca0b86a3b285fc7dd6b040093ccc346344"" width=""300"">",bob,image/png,1520884,2025-03-20 17:44:55+00:00
3,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fpurrfect-perch-cat-scratcher.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T201823Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492719670724&X-Goog-Signature=5dbbec9d52be0f6fb2288804f812adcdbee47e8a6a5e1addeea648e3e2fa7129bf299b4528896dd039eec54da32633622c36ed90f7b93e4b52d400b50f45900a722bd3b159d0dc79ea567fb4ca2e6541028d68eec8a481ba15097fc63df50496bb51439806fc952370c3cbf3577c21f3f61b2f253c1e8c8821f5a31eceeba5fe110b2064706a36cc3a5041639f8673f7572b93195b357609944c892fffa65e0624ed73f27160d2401df695881e58074949c463c150880a9a75a0e7e28d3d144c6ef18e85d763a8b72d0ac45065d68d2a45581c11be30ab60acf4de29f7ca5592664c8a917358b5593520fee2c89cecb062a6071565acaa8f6a2bc3ba7d9f05aa"" width=""300"">",alice,image/png,1235401,2025-03-20 17:45:19+00:00
4,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fchirpy-seed-deluxe-bird-food.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T201823Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492687196980&X-Goog-Signature=af14fcfc1b6e3a81e25df175e3b3d1b8b8be5588ef74f775dcf2cfd266b342e9c1e0184a4bc1b88c37209f27a23f0552dada58ca8edc95f47cc575a7de5678fd419f1f10bead607e37464f74093c24775990072726ad1fae5e923fbf2354967fe10d90149384d3c6e0955b6623eff94bc999b01467456bb94d1189ed76b3e4898858be4d44b5bc2a7f9b97fd4a94e2e823adfdbe2c51c385e13fb0534e8202af59364b0d9c54512fdc571a7c012d2c1f497b27f5f4e77924feddb2d4aab78ca4c2cba5282accf6707117efcf2aa4a3bb9e01815be41c380b9bd327c492b05a7e1d0fdbfbbfd8f3b0cb353165cde6cc42d1a16ac51a33c7b1318d3405cf104399"" width=""300"">",bob,image/png,1591923,2025-03-20 17:44:47+00:00

Then you can filter the rows based on the structured data. And for different content types, you can display them respectively or together.

In [7]:
# filter images and display, you can also display audio and video types
filtered_df = df_image[df_image["author"] == "alice"]
render_images(filtered_df)

/usr/local/lib/python3.11/dist-packages/bigframes/bigquery/_operations/json.py:124: UserWarning: The `json_extract` is deprecated and will be removed in a future
version. Use `json_query` instead.
  warnings.warn(bfe.format_message(msg), category=UserWarning)

# 3. Conduct image transformations

BigFrames Multimodal DataFrame provides image(and other) transformation functions. Such as image_blur, image_resize and image_normalize. The output can be saved to GCS folders or to BQ as bytes.

In [8]:
@bpd.udf(
    input_types=[str, str, int, int],
    output_type=str,
    dataset=DATASET_ID,
    name="image_blur_kaggle",
    bigquery_connection=FULL_CONNECTION_ID,
    packages=["opencv-python-headless", "numpy", "requests"],
)
def image_blur(src_rt: str, dst_rt: str, kx: int, ky: int) -> str:
    import json
    import cv2 as cv
    import numpy as np
    import requests
    
    src_obj = json.loads(src_rt)
    if "access_urls" not in src_obj:
        raise ValueError(f"Missing 'access_urls' in source object. Response: {src_obj}")
    src_url = src_obj["access_urls"]["read_url"]
    
    response = requests.get(src_url, timeout=30)
    response.raise_for_status()
      
    img = cv.imdecode(np.frombuffer(response.content, np.uint8), cv.IMREAD_UNCHANGED)
    if img is None:
        raise ValueError("cv.imdecode failed")
    
    img_blurred = cv.blur(img, ksize=(int(kx), int(ky)))
    success, encoded = cv.imencode(".jpeg", img_blurred)
    
    if not success:
        raise ValueError("cv.imencode failed")
      
    if dst_rt:  # GCS Output Mode
        dst_obj = json.loads(dst_rt)
        if "access_urls" not in dst_obj:
            raise ValueError(f"Missing 'access_urls' in destination object. Response: {dst_obj}")
        dst_url = dst_obj["access_urls"]["write_url"]
        
        requests.put(dst_url, data=encoded.tobytes(), headers={"Content-Type": "image/jpeg"}, timeout=30).raise_for_status()
        return dst_obj["objectref"]["uri"]
    return ""

def apply_transformation(series, dst_folder, udf, *args, verbose=False):
    import os
    dst_folder = os.path.join(dst_folder, "")
    metadata = bbq.obj.fetch_metadata(series)
    current_uri = metadata.struct.field("uri")
    dst_uri = current_uri.str.replace(r"^.*\/(.*)$", rf"{dst_folder}\1", regex=True)
    
    # Bypass synchronous validation via JSON initialization
    dst_blob_df = bpd.DataFrame({"uri": dst_uri})
    dst_blob_df["authorizer"] = FULL_CONNECTION_ID
    dst_blob = bbq.obj.make_ref(bbq.to_json(bbq.struct(dst_blob_df)))

    df_transform = bpd.DataFrame({
        "src_rt": get_runtime_json_str(series, mode="R"),
        "dst_rt": get_runtime_json_str(dst_blob, mode="RW"),
    })
    res = df_transform[["src_rt", "dst_rt"]].apply(udf, axis=1, args=args)
    
    if verbose:
        return res
    
    res_df = bpd.DataFrame({"uri": res})
    res_df["authorizer"] = FULL_CONNECTION_ID
    return bbq.obj.make_ref(bbq.to_json(bbq.struct(res_df)))

# Apply Blur Transformation
df_image["blurred"] = apply_transformation(
    df_image["image"], f"gs://{OUTPUT_BUCKET}/image_blur_transformed/",
    image_blur, 20, 20
)
render_images(df_image[["image", "blurred"]])

/usr/local/lib/python3.11/dist-packages/bigframes/core/log_adapter.py:175: FunctionAxisOnePreviewWarning: Blob Functions use bigframes DataFrame Managed function with axis=1 senario, which is a preview feature.
  return method(*args, **kwargs)
/usr/local/lib/python3.11/dist-packages/bigframes/core/log_adapter.py:175: FunctionAxisOnePreviewWarning: Blob Functions use bigframes DataFrame Managed function with axis=1 senario, which is a preview feature.
  return method(*args, **kwargs)
/usr/local/lib/python3.11/dist-packages/bigframes/core/log_adapter.py:175: FunctionAxisOnePreviewWarning: Blob Functions use bigframes DataFrame Managed function with axis=1 senario, which is a preview feature.
  return method(*args, **kwargs)

In [9]:
# Image resizing and normalizing can be performed similarly by implementing additional cv2 UDFs.

/usr/local/lib/python3.11/dist-packages/bigframes/core/log_adapter.py:175: FunctionAxisOnePreviewWarning: Blob Functions use bigframes DataFrame Managed function with axis=1 senario, which is a preview feature.
  return method(*args, **kwargs)

,image,author,content_type,size,updated,blurred,resized,normalized,blur_resized
0,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-paw-balm.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492703986347&X-Goog-Signature=5f8c50659e2117ce9dc838470214b2a4622a50aa22df7ad766b0110fb4a3369bbed34857568626523489133580b8ab52bee7c7e95b0d1fa8ecfc1f6d748d6dee2893d8b5456aa1d366520ab2897cf4dbd011a7fc1854ef281f54c28a35cad59a0010cc1c9f5eeed6da7c85cde366d98b418ea98a3f8a0ec83ed3bf4158a5348ac3250b0f445b5ab5ab97eecbe25f799ec0a1c466719880ec8ad50e16d01ec2d33980debb992a88b42ffa99f886622d45dd921fc97489b080b625e516106000ed55ab2dbaa04ac28ef1c97d447497f1f30dd2efea4c92d2d22d250203239de2d1da1d5ad0988224b4d76447cb5bf1ce0e104dc9369ffc2ed8abfbd605e79ebaef"" width=""300"">",alice,image/png,1591240,2025-03-20 17:45:04+00:00,"<img src=""https://storage.googleapis.com/bigframes_blob_test/image_blur_transformed%2Fk9-guard-dog-paw-balm.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549023340907&X-Goog-Signature=5629b7eee76f37486002cef7f1db57780852922400d8d47cb838864875ba46568d97cdac09dd6b8f9ab4b0a3102446b1c749bc1a82f6b7115041225117e860061d4980a353f778bf9172d79aed23cf1471deaa2c61c1f97e104877a2d2b8d0e4b131a0f06d2c0c79929de33e0585cbcdf553fbd4ecabf7e5fecda32f97e11f809bd05df1118b6b82b7c441745a5fc4e1bcb4f0d52ed1186c94d66809ee68a4c481342aba17654f1397589227b17246952ce105c751b0d099bf674fa772fcd22456ce1534a2ff9c763009135c1f4a3a10eed92f1a6e66d6c46c5fa05a679cd9bca00558c2ceac4a63ff8d15e51ca2603682216664508abedb5f92e3f823cb4fb4"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_resize_transformed%2Fk9-guard-dog-paw-balm.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549186906659&X-Goog-Signature=a83503cf1de4b802678a0ac122089835a1b27727e2d8474838a4836cc42dc39c8c6aee08b7d145edac3cb762116641cba9c7f539a93e87075763dc526f431950995e6483d5c911d97f0d386d598a097f183d797206c6ef4deb607125d7578a3f98657ee6003329bda5567bad49a7221417c1b628b1007a3e5d01727d9b14b29b1f27cca3f281aedaf40f34d12ca93d9f1d94f6633c13a30dcc3957f3f1ee196801b56b18dc86bdf7f5128a9dfd2af09bf94a20254af4606a55fb7e3b7eb45e9d0be34664195e7cd818b2d5990687fec8e1d9c36f6333e9a49a5399501f46b110fa6e686e1d42bf112f68d2b4e13a0bfcbcd9104510ed513f771ec2053d9bb639"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_normalize_transformed%2Fk9-guard-dog-paw-balm.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549353120386&X-Goog-Signature=b9d8b27e4b05cf5e27afe8c0f8abc9c42fec3128c587324a84ccb94ed8675566f1482224cfdf982f0b236c59fa34a5aa1ed54b3fc4363cde2279244dbe4fb578967366ba0af304052d57a0d88d035ada68b34b723f566eea96874522830435e103acf29ce848a809e447e25f7d7d5ab3893f84931a55945d183aa058fcfaa84991e33c44e8d6e6074a783ee9578fd88325064bf8998830bf5a9f04015e910312c8cbaaf1b539113e6bc595bbd336cf84cc5c8396d8a93f7ffb0eb8b1a7a56ada4f0ef81c5dfc05ca36ec7861e3deef98b5b12a67ba321dd7a0f213d4fdc31f0675eb7031a7980ffbe1dc97ae3699651ef18c59ef2cc25fc071be017fa7441c47"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_blur_resize_transformed%2Fk9-guard-dog-paw-balm.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549346801405&X-Goog-Signature=2044260548b5d07aa084e834c723e9196da0eed8e63c26a248381a3d7874505e3926d78973e99fff4a89dcf34042a4c39e3da508b02b24586141e89243bbe9641982cce474f2fece7e5b2780f7ef94dd1a89d498c162eba2017dd065ee202068a0a004054abbd71524a6e447594a2003f03427db3fd4e66df3dfce42258fea5a8823b7b46d8b15b33938f1b23b4206e79257282d4511d4c72d04f66a1e3acbdad6509871aef992893fa615b2bbab638f80cb1b2ba5610b5811eb8801e06ee904dc02fe4a9740ee5a7d931f0aa96b26e2c1eab25c0d9f3361b89ee4ad1f290611490bd66d9bde6dc90c5adfd0350b8a09c2cb8399c9e3d66ca3abcceb1ef4c3fb"" width=""300"">"
1,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-hot-spot-spray.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492702954473&X-Goog-Signature=987caa66e11b8446c02a240c423145f774d295c19afbe71eba9c3bcd0504525b19723b8d08bb4644f231b3e0b2bcfc13350112e1956d53d957a9986dd742b5f71f5406420da2eda739319eea452088c5138e901a101ad20f682d66245e966da1c6024e68de1e775ea5f395fd744f1717faca8875f89d9cb5eb969a79fb056dab43ada9abac0658bccbc7f72ad2ea293e9d70bf95ac5d81a0dc7bf62220c76fed0274be232c24180ad03f60f89d51eaf7cbec2d6748a94647ec253a9b6d1c95cea8b054872db400e78c930e69fd4ad835f7208ca33a4917ff1b24fcb510fe554792f4cbcaa8c7d4d3f17d1cac843b3f8c181c3e443b6720124055a74479228b14"" width=""300"">",bob,image/png,1182951,2025-03-20 17:45:02+00:00,"<img src=""https://storage.googleapis.com/bigframes_blob_test/image_blur_transformed%2Fk9-guard-dog-hot-spot-spray.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549020470951&X-Goog-Signature=6040bd68fa7a59e5100ecb3bab3d005be6353e45ad856cb7003fbce5c379a4926edb4226cbe7f6347a2172bd7cabe96a27f573e78192712f5472ba7b6fcf3a8abb48bc8376cc1f916cbfa6870f878cf48b5f7ff0b896844c3ca63eab4ff9d926e895f141a25d1718cdfff8ea7dc98a096a245dfbac33e1092af4541e1cc4fc3de5c7d9d62ab4b32ab725476f74f49b40625cca3063eeefb9c03ee2ffddfd2080176435672c2a3206db6c3d1cf826c3011366c4f1dd4db0ad87d6ac392b4c76c4196db4e55d2535f2ebb66b1a23cb90547277027cd482102a1b6036e7a62466733b6ed30215594f4724a838f135e2e413e0c185935761ec0e6033d361aedbc36f"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_resize_transformed%2Fk9-guard-dog-hot-spot-spray.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549187521760&X-Goog-Signature=8bdfcaac843956ea960296c0d03c7e3020aa2810f887d80da7569f0b1828a76097eae9f3a18e0635a6701e651f69bfb8bc56533009d8e384036acd6c3a834b5e5b16b3f9a725a5759df0e504b328e304e53b8eb686252f7946cc6cf3d14a52d9e14e3d37344aa962f52e5be9dd28ea7b6ba20bb341b699bd79ced2d9f829a90cd829dc3288d87cc6310aa4361dc20c28065d50a8f70f293719d97ed8a8e8c1799c1ba6f33a5b2aadb8e2a47b6fb3acf41c204034e7e595491fd9ede24774f0484a0ae50e8e2d404ec37b29e9c6cca2feab0c4c9e67e4923848c8d3a61c59768c0937e264ec635e36a8e5a63d2c7319af46f4ab1bfd550fdf6b1ad4c07cc8e965"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_normalize_transformed%2Fk9-guard-dog-hot-spot-spray.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549359215948&X-Goog-Signature=9365da5cd82f3f428e3fd58e0f3dc49147aa398bba646fefd7e2d24ae130a5a1edb8a333eb22c9d89ecbdc87bede7b244aef1d2d8fc84bbd8240de4656002b23c8c2c149b692e70e3ef5c6772c6a2ecf67436c5a7cad77986f0bf03fec18b1529fb8c93bfae5a3f0f361ea3c66f13330619381d28726b6e717c84aba9296c915cf3ed630ea5fc7ecdf6b6cd7af3f93e222a5b2713acf00a2b04f709ec2c58e6e94b96a64a11891978b2fbaa23e115691a73a931dd6b439d7835dd8840ad7a879c2f8606c2ede1740e676b734f4e08fdddbb6a2e0bf7372f21f6324f3ddb8c22998bdc28309aba74e3810b528f4d3c365c3ec3468a7ac585efdd108c46c6a60b9"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_blur_resize_transformed%2Fk9-guard-dog-hot-spot-spray.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549348094576&X-Goog-Signature=4b5db258dfdd417beb18af774f6ad4e3c2645aca66abbd248fe76dfa3f2bf83900090c0064f864eba26027379895ad99e0e75aa83b957fbb4fc667b0d9e7b6baeb811678118c7016fb828a9924c9ba8c27c045122f683b3fc525e0c27744b8ea3907b9dd8fbcae4e79234548a36c60617f648fc0b65b3949786d57d871e4c01de07a5824d75a290892ccba17e528600c1250eedf89b2958d81096eef7407a63148f29f5b6a3690ad86995e1c5974585095ecadceb218471c68c2527353447b639544c2378e85fc44ff55eb6903950de2530565c7d647c3bc09c6a6aa3c3c65329aa53085ed443dfad094758dd06d7f39d209e83cfc265b03113c9fc431b13017"" width=""300"">"
2,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Ffluffy-buns-chinchilla-food-variety-pack.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492694988945&X-Goog-Signature=ab5e9d751859bee56cec2b9c7279c9f1b3bef256ae2850930006ec8083a623cd96e97e207e84c2487d8e4407544a5c2fdd755e8f187eba93753cb6ef53a3a1de33691829265905e049214f7c828e640d8ed96ff2f20f60c19a044f3cfafd99797f65297703c5bc0f5450f1d9fa9526a017a99c8b174e7af970c5a8d0cab5c1ec15e34ec8efdfe06ce85aa444482e8e289f3d8dc8a5f6e2cbe5c9309e2d2ca80884880f32f27cc7745d909ba40d4c37b6631f71b9d5172a43480e5763a7d844565a084b86dcd772dc5128e238b4ea476070c4ca6d0b748417f3d23a52264c315509d94636dbeb08d152552410de678e3668ea4ea4183b7100f4c8d3d4b1aa9a4a"" width=""300"">",bob,image/png,1520884,2025-03-20 17:44:55+00:00,"<img src=""https://storage.googleapis.com/bigframes_blob_test/image_blur_transformed%2Ffluffy-buns-chinchilla-food-variety-pack.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549019078907&X-Goog-Signature=93ddd73d20863af4bcd6d55d8b08efd24322967276c4c50acc96abceda81aec68addf10d783fdbdac7fe7cfbd7170663bf377ca4a1e2686c52ae46e2f4fc0f4a94e7fe51b9bc3b512fd23d26fdc6a62bcce36c348457b82f65fc8c956d8ef0bf1a14d30d1b61e40f80014d76155d13e051ccbc204360b5d43b19644094f3b9fa0fa2b6d723de301ea490f18929d568d785f53c9f74be51f389ba179bcbe2f6577cc2665e8a90fe5619f33468d3df5b3b8bc1e4c7df97c430d6b2323f7961de687314d62daa4e511d8e0ccf2b0d4d5321b00024163f08ec5999feea0917aee1a33d5b103775fe64350c1fcb4e8aec72fe7c181b9c3c9deae38b19fc8190b25ead"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_resize_transformed%2Ffluffy-buns-chinchilla-food-variety-pack.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549188241967&X-Goog-Signature=8ccefc10cb6fd5194bc2d872fba31ec997e22d8826f309bea7f5266fac43223991b58d95ac65e0b96d5d9de7f1daa817b35abdbbc2785a3d931d1d603ad916bf5d1b1d9d0f809c3dd4714a1f1027407ef0659b3d863ce571ada817019f006b8c56f5a26da1749b3202de18becf7a337e72a1efe16f44c6a946c7196bfcb38b3b6944e31e075a5da9a576c27f840e507eddf9b29264dae15cd5f10d34874a861b4113eecc6af6d3d16f131835f4ddc5592e3adc871c96e0bafa17d9b4c133f697040398d7a6dd438c6c9c8679fed8f78a6e81c5b6001846d62224683c8ca8bf3aa26cd97d0b333a5ba333f0707a528f1e986207852339f48e6f370d492938e92b"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_normalize_transformed%2Ffluffy-buns-chinchilla-food-variety-pack.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549355947800&X-Goog-Signature=42e69641c9371bd2eff79bb51f0d9e4d27960d7e2a3852e0c44740c5a57afb0f026cd43fd4ee1594d09eed2b93b84ddcfd31bf341182b5e862760b8138bfef101d9f747351b6701e699a5bc406bf10125c5d29f2d6564f9acc7eb4e5197f8fdac6abb45480966b168077d0a69d9941b96ca2517a444e7e591422ec8c2a0ed8b7dc0c839af585593e73eb4f4a372f8f41d2e5bf6bed8768c46325b27bab10c4a56813265ef15b18b61f37846448c2e7890847f6b65d03e745f89094d06d6daf5820c49f60839468a5410d5d5f93015acca4fe2912a9f7c372c0b7374ca65de28bea669d8032eff08e3f575590ead5dfb6f84ac49f851ecde0298882f7e3912eb2"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_blur_resize_transformed%2Ffluffy-buns-chinchilla-food-variety-pack.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549351340006&X-Goog-Signature=b2af2667d8d9026e68bb9fe6b4e9b56d0ec35b20f34490db21c39b24d139321fd31936265270ab8dceed0857c53f5d8639f7438be45cb5788d8cd2588d42e68cc86df3f81de4ad1f356263ff6fd0921d3f237b0135b37e6382c72921a5914043a72d3b6550b6ec6231cc05c9d3d522bea46c65423ce0b64b03eeaa295996c8a8e26f480e55c95ac2aec47567ff0f07b84d993b5b6f56e9caca5109932c184ed234cb5a57b1ab740f2f4164d304179242d3190b10a97a436097d8c6fbf7325fa5e04b2d65ed3fe3b00471cfb27a82ac7f3a92d0c00afe201c2a7cbec877a762c7d057bf3493e295cadefac95edc5345073ed41c518499d2bc257f92f0215ace56"" width=""300"">"
3,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fpurrfect-perch-cat-scratcher.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492719670724&X-Goog-Signature=a152ee4011f72e7f0a09a2f883dc6abeb1179f32020930e1def252e5aad559ecf3cb96abd8e134f14a7d39c71ab9fec9411d9b1c29400d06313dc871c2500ed22033c561def13df3525eda40c10b9956ec22dd06ed9148e15e4af699b8e715c2308b92303c0b57a66b9b02473abd83565731dced27af52db48b2ecc8bdecbae16b512c50c30d30fc17ab8f21e471b904b93d97a2e1652e6e70626d75aeecdb13da6ef82993a6df033dfc341127bd1d387275ef345d89b60caafdecb548126aa7f90ef6c74beb0ac0f18902de474a8e0b289e306d0f824be87d1131ed4aa093cd52e486e1dae05c6c9b3e364aec6b65d9b93294e588ff6ecdc25b75ca0a488ba2"" width=""300"">",alice,image/png,1235401,2025-03-20 17:45:19+00:00,"<img src=""https://storage.googleapis.com/bigframes_blob_test/image_blur_transformed%2Fpurrfect-perch-cat-scratcher.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549018389386&X-Goog-Signature=1f1c5af6da1c990838c0a95aedea3aa65ee34b2ca70d8221511880eac073548a5f15eb993dbaf4a92469391933875d3b198b3a146181c6acfd96798f65673699724e103c131c051094f3b5721af5a79e997244c19576ce115b826565baedeb2cc08b6cc93d762ddfdc2750596d567df1c65ef32fd56ea4bec4463724107e07e2b47a3dcf50fafc1ab5d30fb8aa24024011895224c437e6f78c2cf2d4e23e09eae5c2d9ce49de627f2c5b2f90509b9532070bb426fcdd64e2892440ca43d370415ac30cea79fed08716666d40423d0631eb3cacb545a95cfe23bd47690d63610d1409cc1d508ce29a465146408dde3ce7f6b986495542f68439d06796dc7ba792"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_resize_transformed%2Fpurrfect-perch-cat-scratcher.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549186140674&X-Goog-Signature=3888ecd32b4b27e8a78f8c4b674cc6ce1990d66730cc1b37fa0814a948ab09b6b9dd49ee960e9a4dc4bb77cb1b3fb5c87e0b7e23e376eef8b4dc8673c6edae6720eb7e07b52ad172e4c5518f340ce58a3adead7178051b553b9d21df0f7c2c147c922d43ec73ba36bcad88805d84f66ddbe1f2cca3338f707ce38d22bf0bb78e86fb97eaa9e8df8a923320919fa5f8b99576aaf2eab09cfdd66da2c0c82986c7df3271d0f2877ea95429018aaafd4e10ac670d25a7568d175aeab74def3371c7064cc019ee8e0fc4ca1e4c6e718c7925051b9fb35b3095dcde072043b2a29e26e85b603fcd7ee1569eaf84054e9a7a1572100f61aa38ebe4ad306bb128a9bd19"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_normalize_transformed%2Fpurrfect-perch-cat-scratcher.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549353981426&X-Goog-Signature=a25d1c75eef237aa75032402319dd081e0c9f15cdd95b79a31b8245d63b17752756cb356df7c69390ac05b496aac3fce22c501614660a06a18a148ac332fc28f245b3029405edbd40f2887dc76be5cbcf107c3bdd4725b93359a91adf775d6b827ad0413ccdf30dd1541c23bef40136622bea484ff16cb8adca54467515d6df88ffff70f5295f4801c2eba2cfd3e2b3606c53bc4257e7dcc51983c1de7edc8a2313380b7bfb8ac42f2460fcce281b6ad11ccb7e4edba23227f0da9181cbeeb0380302134659799ca8704c1b8dba92557d84ef3222fcfacc7584d65084ba847952d4676894d6c9f90ae692128721b48697c93baeb988d639338450a2bdad89a44"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_blur_resize_transformed%2Fpurrfect-perch-cat-scratcher.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203600Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1755549347689362&X-Goog-Signature=5bd305a1286eae578a5c7aebe3fe718ba4a221d98b2aa38aae42d25572af2990f3cc845808576f97f350a2f799a740ceb9b661d6a02d1e22029f35a4ced0c1f82d6343b9fc3132b46a7754ba6571af9186be033831f98974b75967156e97fe3e3da348521624ef9714086bb9ea67ff1cbdf721b0fb922420ea14b1a991dbac5246ec53e5156a11bccb6298aea948bb3fcedd320e468f932f3f1cbd244d87fb9ea1b4b92c9517820e4cc3a2f013f0994ce33e8ca60fe42f2de3f59c15a7c4fb98123c7f889fb1966fd20a79237d8bb95c37c56c3f2e33236d9b1c6d6aa0b08ea6e583329cefe8e76a89d062877a5046fe8f222ed1d8ea263ecca5daea54300afc"" width=""300"">"

# 4. Use LLM models to ask questions and generate embeddings on images

In [10]:
from bigframes.ml import llm
gemini = llm.GeminiTextGenerator()

/usr/local/lib/python3.11/dist-packages/bigframes/core/log_adapter.py:175: FutureWarning: Since upgrading the default model can cause unintended breakages, the
default model will be removed in BigFrames 3.0. Please supply an
explicit model to avoid this message.
  return method(*args, **kwargs)

In [11]:
# Ask the same question on the images
df_image = df_image.head(2)
answer = gemini.predict(df_image, prompt=["what item is it?", "what color is the picture?"])
render_images(answer[["ml_generate_text_llm_result", "image"]])

/usr/local/lib/python3.11/dist-packages/bigframes/core/array_value.py:108: PreviewWarning: JSON column interpretation as a custom PyArrow extention in
`db_dtypes` is a preview feature and subject to change.
  warnings.warn(msg, bfe.PreviewWarning)

,ml_generate_text_llm_result,image
0,The item is a tin of K9 Guard Dog Paw Balm.,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-paw-balm.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203711Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492703986347&X-Goog-Signature=06718c570f3a86457a786ed768e5deede983ae58e79ea4c1ff7793a6d4f7693c111340cf05a4f7dd8a968340f4c2f2a992240dec3af83725b3983a8c47f663e5d800d2af7144f8d5b2b3097ac780fa66398dd95696691f6eddadfba15b77da3c16ee5d1b700378e8fc1e2d574eea0e7adf42fa23c9e28fda9aa9c97a3ec2e461afbbbd45a9c9a0c2a50f0cd561159cae73c1d7dcf6df215a7c39fb9e4c3966364ee7c5f95f16f0e733d02ddc6e1badfbce0edc89f426a79af2af8c66e743df3811d6e7990e3a692d78461939d5ab6b393e88bc32e9bcc56764f114898e6bab921346783ff42d17cbf2f04366a21834a568a52cf32a5df81654ddd000f2ac1c34"" width=""300"">"
1,The item is a bottle of K9 Guard Dog Hot Spot Spray.,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-hot-spot-spray.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203711Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492702954473&X-Goog-Signature=141c42af27dc86e89a3075f3af82c75ee5afb817e0850586a96cdb3ee180c22a8ed09f0a8e1a3c5d632846cbdfd10d71600c8f33a699b5a6c0dd6f34784b4d1d8d39a9ba9e85bff3c984c29b5cd628551149428d3d2f96253d994d0e4005527207c5fe11d681e840a98601ca7858ef9f9b4680a477621684c1f2295bb49a95b40d04fb6fae3ab4383210145da8dcd9723d442314c9d60225470f5d8b017073a5626ccf77a2fb644432ece39b38f3a2ada019f20e6a61fb026962521d4f73ac92229f575eb21d18c52d2200cb4f14b2f2dfb650c52023277d7656159e99212ce90729d946caf847704c5cdaf467202a3bef13d2f1bcd558f2647da4a1d049f36b"" width=""300"">"

In [12]:
# Ask different questions
df_image["question"] = ["what item is it?", "what color is the picture?"]

In [13]:
answer_alt = gemini.predict(df_image, prompt=[df_image["question"], df_image["image"]])
render_images(answer_alt[["ml_generate_text_llm_result", "image"]])

/usr/local/lib/python3.11/dist-packages/bigframes/core/array_value.py:108: PreviewWarning: JSON column interpretation as a custom PyArrow extention in
`db_dtypes` is a preview feature and subject to change.
  warnings.warn(msg, bfe.PreviewWarning)

,ml_generate_text_llm_result,image
0,The item is a tin of K9 Guard Dog Paw Balm.,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-paw-balm.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203757Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492703986347&X-Goog-Signature=12cfd68cb145aef7edd54a3b0f03944424776133f09fc277c6bce2a8a267116ac6911b59615d0fce3ebf2e901d5ae847dbb414f9d524ab42b924a496a81bf0eff4b22c60b89adef7d863f85f9680c05d31afab795635e30ab38a297a221b6374df190bdbbdaed90c5bcd6b79f63a8d9c5f7c4db1c981b2a03fb5808feaa8e4d2e036a11f9d19c9b3fb94471562cbd2329e1a1ebc6e841111c5f90a847da63e362d6ff8d878ddc106aa13932143c2b8eb0e3c222a2bcb4ec1b46bc032678e872be7a3325e5e3db76b6dc81e0fc189bf0a4fc30e8c508fc1c12c5d61d2c9601339657a318a4b0abde83d5ca7f73387342de33399e2d8b62c67d549e09507f09c4e"" width=""300"">"
1,"The picture has colors such as white, gray, and a light blue (cyan).","<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-hot-spot-spray.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20250818%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250818T203757Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492702954473&X-Goog-Signature=b597801312fce93103bf273c7669e665573880dca47521adb16cbb6864ab2f4a057cf060519acecc9be14695ea0c5d4848ea631f53dfe6df89a390789faa4d946a2828f7112f508be8f6b40ede1fa4cd565fc9738d73ddabcaf08e7467bd58b54a0482061fc0c522f9b74a7c4402aba788d9c45b6c0416f639a275a4d70cfa15ae258343eb3c17170ff9227b1ea6b020b5ed5e95f0db4df10292537bb19afdf03007c0b05c026343e3c7ea48c743b65c1cdf13422f4c02e258a623fafd8f083ac52afb9d5787b822913de2c58a03e93ad3323b44ff16327b689e1cc6ab7590a358a82b8f70f967898f4bfd41bdafd446e8dfd83b7704094d0146bc07a0934427"" width=""300"">"

In [14]:
# Generate embeddings.
embed_model = llm.MultimodalEmbeddingGenerator()
embeddings = embed_model.predict(df_image["image"])
embeddings

/usr/local/lib/python3.11/dist-packages/bigframes/core/log_adapter.py:175: FutureWarning: Since upgrading the default model can cause unintended breakages, the
default model will be removed in BigFrames 3.0. Please supply an
explicit model to avoid this message.
  return method(*args, **kwargs)
/usr/local/lib/python3.11/dist-packages/bigframes/core/array_value.py:108: PreviewWarning: JSON column interpretation as a custom PyArrow extention in
`db_dtypes` is a preview feature and subject to change.
  warnings.warn(msg, bfe.PreviewWarning)

,ml_generate_embedding_result,ml_generate_embedding_status,ml_generate_embedding_start_sec,ml_generate_embedding_end_sec,content
0,[ 0.00638822 0.01666385 0.00451817 ... -0.02...,,<NA>,<NA>,"{""access_urls"":{""expiry_time"":""2025-08-19T02:3..."
1,[ 0.00973672 0.02148364 0.00244308 ... 0.00...,,<NA>,<NA>,"{""access_urls"":{""expiry_time"":""2025-08-19T02:3..."